src/jobs_manager_app/urls.py
from django.conf.urls import patterns, url
from jobs_manager_app import views

urlpatterns = patterns(
    '',
    url(r'^project/$',
        views.project.index, name='project_index'),
    url(r'^project/(?P<project_id>\d+)/$',
        views.project.detail, name='project_detail'),
    url(r'^project/(?P<project_id>\d+)/update/$',
        views.project.update, name='project_update'),
    url(r'^project/create/$',
        views.project.update, name='project_create'),
    url(r'^project/(?P<project_id>\d+)/delete/$',
        views.project.delete, name='project_delete'),

    url(r'^assignment/$',
        views.assignment.index, name='assignment_index'),
    url(r'^assignment/(?P<assignment_id>\d+)/$',
        views.assignment.detail, name='assignment_detail'),
    url(r'^assignments/(?P<assignment_id>\d+)/update/$',
        views.assignment.update, name='assignment_update'),
    url(r'^assignment/(?P<project_id>\d+)/create/$',
        views.assignment.update, name='assignment_create'),
    url(r'^assignment/(?P<assignment_id>\d+)/delete/$',
        views.assignment.delete, name='assignment_delete'),

    url(r'^assignment/(?P<assignment_id>\d+)/estimate/$',
        views.assignment.estimate, name='assignment_estimate'),
    url(r'^assignment/(?P<assignment_id>\d+)/confirm/$',
        views.assignment.confirm_estimate, name='assignment_confirm_estimate'),
    url(r'^assignment/(?P<assignment_id>\d+)/state_forward/$',
        views.assignment.state_forward, name='assignment_state_forward'),
    url(r'^assignment/(?P<assignment_id>\d+)/toggle_hold/$',
        views.assignment.toggle_hold, name='assignment_toggle_hold'),
    url(r'^assignment/(?P<assignment_id>\d+)/hold_payment/$',
        views.assignment.hold_payment, name='assignment_hold_payment'),

    url(r'^task/$', views.task.index, name='task_index'),
    url(r'^task/(?P<task_id>\d+)/$',
        views.task.detail, name='task_detail'),
    url(r'^task/(?P<task_id>\d+)/update/$',
        views.task.update, name='task_update'),
    url(r'^task/(?P<assignment_id>\d+)/create/$',
        views.task.update, name='task_create'),
    url(r'^task/(?P<task_id>\d+)/delete/$',
        views.task.delete, name='task_delete'),
    url(r'^task/(?P<task_id>\d+)/close/$',
        views.task.close_task, name='task_close'),

    url(r'^user/$', views.user.index, name='user_index'),
    url(r'^user/(?P<user_id>\d+)/$',
        views.user.detail, name='user_detail'),

    url(r'^comment/(?P<assignment_id>\d+)/create_from_assignment/$',
        views.comment.create_from_assignment, name='comment_from_assignment'),
    url(r'^comment/(?P<task_id>\d+)/create_from_task/$',
        views.comment.create_from_task, name='comment_from_task'),

    url(r'^notification/user_list/$',
        views.notification.user_notif_list, name='notif_user_list'),
    url(r'^notification/toggle_seen/$',
        views.notification.toggle_mark_as_read, name='notif_toggle_seen'),

    )

src/jobs_manager_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _


class Project(models.Model):
    customer = models.ForeignKey(User)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    created = models.DateField(auto_now_add=True)
    modified = models.DateField(auto_now=True)

    def __unicode__(self):  # Python 3: def __str__(self):
        # When Django displays some object of this class,
        # it will show the returned value.
        return self.name


class Assignment(models.Model):
    dev = models.ForeignKey(User)
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=200)
    requirements = models.TextField()
    STATE = {
        0: {'state': _('Assignment created'), 'next': _('Price/ETA proposal'),
            'desc': ''},
        1: {'state': _('Offer proposed'), 'next': _('Confirmation'),
            'desc': ''},
        -1: {'state': _('Assignment rejected'),
             'next': _('Price/ETA reevaluation'), 'desc': ''},
        2: {'state': _('Assignment confirmed'), 'next': _('Working'),
            'desc': ''},
        -2: {'state': _('Assignment in hold'), 'next': _('Meeting conditions'),
             'desc': ''},
        3: {'state': _('Assignment completed'), 'next': _('Payment'),
            'desc': ''},
        -3: {'state': _('Payment in hold'), 'next': _('Payment'),
             'desc': ''},
        4: {'state': _('Assignment paid'), 'next': _('Closure'),
            'desc': ''},
        5: {'state': _('Assignment closed'), 'next': _('Closed'),
            'desc': ''},
    }

    int_state = models.IntegerField(default=0)
    deal_comment = models.TextField(blank=True)
    price = models.FloatField(blank=True, null=True)
    eta = models.DateField(blank=True, null=True)
    delivery_date = models.DateField(blank=True, null=True)
    payment_date = models.DateField(blank=True, null=True)
    close_date = models.DateField(blank=True, null=True)
    created = models.DateField(auto_now_add=True)
    modified = models.DateField(auto_now=True)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name


class Task(models.Model):
    assignment = models.ForeignKey(Assignment)
    colaborator = models.ForeignKey(User, blank=True, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    priority = models.IntegerField(default=1)
    STATE = (
        (False, _('Pending')),
        (True, _('Completed'))
        )
    bool_completed = models.BooleanField(default=False, blank=True,
                                         choices=STATE)
    created = models.DateField(auto_now_add=True)
    modified = models.DateField(auto_now=True)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name


class Comment(models.Model):
    assignment = models.ForeignKey(Assignment, blank=True, null=True)
    task = models.ForeignKey(Task, blank=True, null=True)
    user = models.ForeignKey(User)
    comment = models.TextField()
    attachment = models.FileField(upload_to='documents/%Y/%m/%d', blank=True,
                                  null=True)
    created = models.DateField(auto_now_add=True)
    modified = models.DateField(auto_now=True)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.comment[0:20]


class Notification(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=200)
    description = models.TextField()
    NOTIF_TYPE = (
        (0, _('New task')),
        (1, _('New assignment')),
        (2, _('Negotiation process')),
        (3, _('Closed task')),
        (4, _('Comment in task')),
        (5, _('Comment in assignment')),
        )
    int_type = models.IntegerField(choices=NOTIF_TYPE)
    bool_seen = models.BooleanField(default=False)
    created = models.DateField(auto_now_add=True)
    modified = models.DateField(auto_now=True)

    def __unicode__(self):  # Python 3: def __str__(self):
        return self.name

src/jobs_manager_app/templates/jobs_manager_app/assignment_list.html
{% extends "jobs_manager_app/base.html" %}
{% load i18n %}

{% block content %}

{% if assignment_list.paginator.num_pages > 1 %}
<nav>
  <ul class="pagination" style="float: right; margin-top: 0px;">
        {% if assignment_list.has_previous %}
			<li><a href="?page={{ assignment_list.previous_page_number }}" style="color: green">&laquo;</a></li>
		{% else %}
			<li class="disabled"><span>&laquo;</span></li>
        {% endif %}
		
		{% for number in assignment_list.paginator.page_range %}
			{% if assignment_list.number == number %}
				<li class="active"><a href="#" style="background-color: green; border-color: lightgreen">{{ number }}</a></li>
			{% else %}
				<li><a href="?page={{ number }}" style="color: green;">{{ number }}</a></li>
			{% endif %}
		{% endfor %}
		
        {% if assignment_list.has_next %}
            <li><a href="?page={{ assignment_list.next_page_number }}" style="color: green;"> &raquo;</a></li>
		{% else %}
			<li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
</nav>
{% endif %}

<table class="table table-hover table-condensed">
	<tr>
		<th>{% trans "Name" %}</th>
		<th>{% trans "Project" %}</th>
		<th>{% trans "Dev" %}</th>
		<th>{% trans "State" %}</th>
		<th>{% trans "Price (€)" %}</th>
		<th>{% trans "ETA" %}</th>
		<th>{% trans "Action" %}</th>
		<th>{% trans "Created" %}</th>
	</tr>
	{% for assignment in assignment_list %}
	<tr>
		<td>
			<a href="{% url 'jobs_manager_app:assignment_detail' assignment.id %}"> {{ assignment.name }}</a>
		</td>
		<td>
			<a href="{% url 'jobs_manager_app:project_detail' assignment.project.id %}" class="link-project">{{ assignment.project.name }}</a>
		</td>
		<td><a href="{% url 'jobs_manager_app:user_detail' assignment.dev.id %}" class="link-user">{{ assignment.dev }}</td>
		<td>{{ assignment.get_int_state_display.state }}</td>
		<td>{{ assignment.price|default_if_none:"N/A" }}</td>
		<td>{{ assignment.eta|default_if_none:"N/A" }}</td>
		<td>
			<a href="{% url 'jobs_manager_app:assignment_update' assignment.id %}"> <span class="glyphicon glyphicon-edit edit"></span></a>
			<a href=# data-toggle="modal" data-target="#delete-{{ assignment.id }}"> <span class="glyphicon glyphicon-remove delete"></span></a>
		</td>
		<td>{{ assignment.created }}</td>
	</tr>
	
	<div class="modal fade" id="delete-{{ assignment.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="myModalLabel">{{ assignment.name }}</h4>
				</div>
				<div class="modal-body">
					<form action="{% url 'jobs_manager_app:assignment_delete' assignment.id %}" method="post" role="form">
						{% csrf_token %}
					    {% trans "Are you sure you want to delete this assignment?" %}
					    <div style="text-align: right">
					    	<button class="btn" style="background-color: darkred; color: white;" type="submit">{% trans "Delete" %}</button>
					    </div>
					</form>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
</table>
{% endblock content %}

src/jobs_manager_app/templates/jobs_manager_app/login.html
{% extends "jobs_manager_app/base.html" %}
{% load i18n %}

{% block content %}

{% if form.errors %}
	<div class="alert alert-danger alert-dismissible">
		<button type="button" class="close" data-dismiss="alert">
			<span aria-hidden="true">&times;</span>
			<span class="sr-only">Close</span>
		</button>
		<span class="glyphicon glyphicon-warning-sign"> </span>
		{% trans "Your username and password didn't match. Please try again." %}
	</div>
{% endif %}

<div style="text-align: center; margin: 7em;">
<form method="post" action="{% url 'django.contrib.auth.views.login' %}" class="form-inline" role="form">
{% csrf_token %}
	<div class="input-group" style="margin-right:0.5em">
		<label class="sr-only" for="{{ form.username.id_for_label }}">{% trans "Username" %}</label>
		<div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
		<input type="text" name="{{ form.username.name }}" class="form-control" id="{{ form.username.id_for_label }}" placeholder="{% trans "Username" %}">
	</div>
	<div class="input-group" style="margin-right:0.5em">
		<label class="sr-only" for="{{ form.password.id_for_label }}">{% trans "Password" %}</label>
		<div class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></div>
		<input type="password" name="{{ form.password.name }}" class="form-control" id="{{ form.password.id_for_label }}" placeholder="{% trans "Password" %}">
	</div>
	<button type="submit" class="btn" style="color: white;">{% trans "Sign in" %}</button>
	<input type="hidden" name="next" value="{{ next }}" />
</form>
</div>

{% endblock %}

src/jobs_manager_app/templates/jobs_manager_app/project_detail.html
{% extends "jobs_manager_app/base.html" %}
{% load i18n %}

{% block content %}

<div class="row">
	<div class="col-md-2">
		<p style="margin-top: 60px">
			<span class="glyphicon glyphicon-globe" style="color: darkblue;"> </span> {% trans "Website:" %} <br>
			<a href="{{ project.website }}" class="link-project"> {{ project.website }}</a>
		</p>
		<br>
		<p>
			<span class="glyphicon glyphicon-user" style="color: darkblue;"> </span> {% trans "Customer:" %} <br>
			<a href="{% url 'jobs_manager_app:user_detail' project.customer.id %}" class="link-user"> {{ project.customer.username }}</a>
		</p>
		<br>
		<p>
			<span class="glyphicon glyphicon-calendar" style="color: darkblue;"> </span> {% trans "Created:" %} <br>
			{{ project.created }}
		</p>
			
	</div>
	
	<div class="col-md-8">
		<div class="row">
			<h3><span style="background-color: darkblue; padding-right: 10px; margin-right: 8px;"> </span> {{ project.name }}</h3>
		</div>
		<div class="row">
			{% trans "Description:" %}<br>
			<div style="border: 1px solid gainsboro; border-radius: 6px; padding: 7px; margin-bottom: 4px; margin-left: 5px;">
				{{ project.description|linebreaksbr }}
			</div>
		</div>
		<div class="row">
			<div style="float: right">
				<span class="glyphicon glyphicon-pushpin" style="color: darkblue;"> </span> {% trans "Assignments:" %} {{ project.assignment_set.count }}
			</div>
		</div>
		
	</div>
	<div class="col-md-2"></div>
</div>

<br>
<br>
<hr>
<br>
<br>

<div class="row">
	<div class="row">
		<div class="col-md-6">
			<h3 style="margin-bottom:15px;">{% trans "Assignments" %} <a href="{% url 'jobs_manager_app:assignment_create' project.id %}" class="btn btn-md btn-assignment" style="float:right"> <span class="glyphicon glyphicon-plus create"> </span></a></h3>
		</div>
		<div class="col-md-6"></div>
	</div>
	
	{% for x in project.assignment_set.all %}
	{% cycle '<div class="row">' '' %}
	<div class="col-md-6">
		<div class="panel panel-assignment">
			<div class="panel-heading">
				<h3 class="panel-title">
					<a href="{% url 'jobs_manager_app:assignment_detail' x.id %}" >
						{{x.name}}
						{% if x.int_state == 5 %}{% trans "(Closed)" %}{% endif %}
					</a>
					<div style="float: right">
						<a href="{% url 'jobs_manager_app:user_detail' x.dev.id %}" >{{ x.dev }}</a>
					</div>
				</h3>
			</div>
			<div class="panel-body">
				<div style="float: right; border: 1px solid gainsboro; border-radius: 3px; padding: 5px; margin-left: 5px; margin-bottom: 5px;" >
					{% trans "ETA:" %} {{ x.eta|default_if_none:"N/A" }}<br>
					{% trans "Price:" %} {{ x.price|default_if_none:"N/A" }} €
				</div>
				{{x.requirements|linebreaksbr}}
			</div>
		</div>
	</div>
	{% if forloop.last and not forloop.counter|divisibleby:2 %}
		<div class="col-md-6"></div>
		</div>
	{% endif %}
	{% cycle '' '</div>' %}
		
	{% endfor %}
</div>

{% endblock content %}

src/jobs_manager_app/templates/jobs_manager_app/task_detail.html
{% extends "jobs_manager_app/base.html" %}
{% load i18n %}

{% block content %}

<div class="row">
	<div class="col-md-2">
		<p style="margin-top: 60px">
			<span class="glyphicon glyphicon-book" style="color: goldenrod;"> </span> {% trans "Project:" %} <br>
			<a href="{% url 'jobs_manager_app:project_detail' task.assignment.project.id %}" class="link-project"> {{ task.assignment.project }}</a>
		</p>
		<p>
			<span class="glyphicon glyphicon-pushpin" style="color: goldenrod;"> </span> {% trans "Assignment:" %} <br>
			<a href="{% url 'jobs_manager_app:assignment_detail' task.assignment.id %}" class="link-assignment"> {{ task.assignment }}</a>
		</p>
		<br>
		<p>
			<span class="glyphicon glyphicon-pencil" style="color: goldenrod;"> </span> {% trans "Dev:" %} <br>
			<a href="{% url 'jobs_manager_app:user_detail' task.assignment.dev.id %}" class="link-user"> {{ task.assignment.dev.username }}</a>
		</p>
		{% if task.colaborator %}
			<p>
				<span class="glyphicon glyphicon-thumbs-up" style="color: goldenrod;"> </span> {% trans "Colaborator:" %} <br>
				<a href="{% url 'jobs_manager_app:user_detail' task.colaborator.id %}" class="link-user"> {{ task.colaborator.username }}</a>
			</p>
		{% endif %}
		<br>
		<p>
			<span class="glyphicon glyphicon-calendar" style="color: goldenrod;"> </span> {% trans "Created:" %} <br>
			{{ task.created }}
		</p>
			
	</div>
	
	<div class="col-md-8">
		<div class="row">
			<h3><span style="background-color: goldenrod; padding-right: 10px; margin-right: 8px;"> </span> {{ task.name }}</h3>
		</div>
		<div class="row">
			{% trans "Description:" %}<br>
			<div style="border: 1px solid gainsboro; border-radius: 6px; padding: 7px; margin-bottom: 4px; margin-left: 5px;">
				{{ task.description|linebreaksbr }}
			</div>
		</div>
		<div class="row">
		{% trans "Priority:" %} {{ task.priority }}
			<div style="float: right">
				{% if task.bool_completed %}
					<span class="glyphicon glyphicon-lock" style="color: goldenrod;"></span> <strong>{% trans "Completed" %}</strong>
				{% endif %}
			</div>
		</div>
		
	</div>
	<div class="col-md-2">
		{% if not task.bool_completed %}
			<form action="{% url 'jobs_manager_app:task_close' task.id %}" method="post" role="form">
				{% csrf_token %}
				<button type="submit" class="btn" style="background-color: goldenrod; color: white; margin-top: 5.4em;"><span class="glyphicon glyphicon-lock"></span> {% trans "Close task" %} </button>
			</form>
		{% endif %}
	</div>
</div>

<br>
<br>
<hr>
<br>
<br>




<h3 style="padding-bottom:10px;">Comments</h3>
{% for x in task.comment_set.all %}
	<div class="row">
		<div class="col-md-10">
			<div class="panel panel-{{tag}}">
				<div class="panel-body">{{x.comment|linebreaksbr}}</div>
			</div>
		</div>
		<div class="col-md-2">
			<div class="row">
				{% if x.attachment %}
						<a href="{{ MEDIA_URL }}{{ x.attachment }}" title="{% trans "Attachment" %}"> <span class="glyphicon glyphicon-paperclip" style="color: goldenrod;"> </span> </a>
				{% endif %}
				{{ x.user }}
			</div>
			<div class="row" style="margin-top: 0.3em">
				{{ x.created }}
			</div>
		</div>
	</div>
{% endfor %}
{% endblock content %}



{% block form %}
<hr>
<br>

<form action="{% url 'jobs_manager_app:comment_from_task' task.id %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
	<div class="input-group"">
		<span class="input-group-addon">{% trans "Comment" %}</span>
		<textarea rows="3" name="{{ comment_form.comment.name }}" class="form-control" placeholder="{% trans "Place your comment" %}" id="{{ form.comment.id_for_label }}">{{ comment_form.comment.value|default_if_none:"" }}</textarea>
	</div>
	<br>
	<div class="input-group" style="margin-left: 50rem;">
		<input type="file" name="{{ comment_form.attachment.name }}" value="{{ comment_form.attachment.value }}" class="form-control" id="{{ form.attachment.id_for_label }}">
		<span class="input-group-addon">{% trans "Attachment" %}</span>
	</div>
	<br>
	<input type="submit" value="{% trans "Post" %}" class="btn" style="color: white; float: right;">
</form>

{% endblock form %}

src/jobs_manager_app/templates/jobs_manager_app/user_detail.html
{% extends "jobs_manager_app/base.html" %}
{% load i18n %}

{% block content %}

<div class="row">
	<div class="col-md-2">
		<p style="margin-top: 60px">
			<span class="glyphicon glyphicon-book" style="color: grey;"> </span> {% trans "Projects:" %}
			<a href="{% url 'jobs_manager_app:project_index' %}" class="link-project"> {{ user.project_set.count }}</a>
		</p>
		<p>
			<span class="glyphicon glyphicon-pushpin" style="color: grey;"> </span> {% trans "Assignments:" %}
			<a href="{% url 'jobs_manager_app:assignment_index' %}" class="link-assignment"> {{ user.assignment_set.count }}</a>
		</p>
		<p>
			<span class="glyphicon glyphicon-list-alt" style="color: grey;"> </span> {% trans "Task:" %}
			<a href="{% url 'jobs_manager_app:assignment_index' %}" class="link-task"> {{ user.task_set.count }}</a>
		</p>
		<br>
		<p>
			<span class="glyphicon glyphicon-calendar" style="color: grey;"> </span> {% trans "Joined:" %}<br>
			{{ user.date_joined|date:"j-M-Y " }}
		</p>
			
	</div>
	
	<div class="col-md-8">
		<div class="row">
			<h3><span style="background-color: grey; padding-right: 10px; margin-right: 8px;"> </span> {{ user.username }}</h3>
		</div>
		<div class="row">
			<div style="border: 1px solid gainsboro; border-radius: 6px; padding: 7px; margin-bottom: 4px; margin-left: 5px;">
				<div class="row" style="margin-bottom: 5px;">
					<div class="col-md-6" style="text-align: right"> {% trans "First Name:" %}</div>
					<div class="col-md-6">{{ user.first_name }}</div>
				</div>
				<div class="row" style="margin-bottom: 5px;">
					<div class="col-md-6" style="text-align: right"> {% trans "Last Name:" %}</div>
					<div class="col-md-6">{{ user.last_name }}</div>
				</div>
				<div class="row" style="margin-bottom: 5px;">
					<div class="col-md-6" style="text-align: right"> {% trans "e-mail:" %}</div>
					<div class="col-md-6">{{ user.email }}</div>
				</div>
				<div class="row" style="margin-bottom: 5px;">
					<div class="col-md-6" style="text-align: right"> {% trans "Groups:" %}</div>
					<div class="col-md-6">
						{% for x in user.groups.all %}
							{{ x }}{% if not forloop.last %}, {% endif %}
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div style="float: right">
				{% if user.is_active %}
					<span class="glyphicon glyphicon-thumbs-up" style="color: grey;"> </span> {% trans "Active user" %}
				{% else %}
					<span class="glyphicon glyphicon-thumbs-down" style="color: grey;"> </span> {% trans "Inactive user" %}
				{% endif %}
			</div>
		</div>
		
	</div>
	<div class="col-md-2"></div>
</div>

<br>
<br>
<hr>
<br>
<br>


<!-- PROJECTS -->

{% if user.project_set.count != 0 %}
<div class="row">
	<div class="row">
		<div class="col-md-6">
			<h3 style="margin-bottom:15px;">{% trans "Projects" %} </h3>
		</div>
		<div class="col-md-6"></div>
	</div>
	
	{% for x in user.project_set.all %}
		{% cycle '<div class="row">' '' %}
		<div class="col-md-6">
			<div class="panel panel-project">
				<div class="panel-heading">
					<h3 class="panel-title">
						<a href="{% url 'jobs_manager_app:project_detail' x.id %}" >
							{{x.name}}
						</a>
					</h3>
				</div>
				<div class="panel-body">
					{% if x.website != 0 %}
						<div style="float: right; border: 1px solid gainsboro; border-radius: 3px; padding: 5px; margin-left: 5px; margin-bottom: 5px;" >
							<a href="{{ x.website }}" >{{ x.website }}</a>
						</div>
					{% endif %}
					{{x.description|linebreaksbr}}
				</div>
			</div>
		</div>
		{% if forloop.last and not forloop.counter|divisibleby:2 %}
			<div class="col-md-6"></div>
			</div>
		{% endif %}
		{% cycle '' '</div>' %}
	{% endfor %}
</div>
{% endif %}
<!-- END PROJECTS -->



<!-- ASSIGNMENTS -->
{% if user.assignment_set.count != 0 %}
<div class="row">
	<div class="row">
		<div class="col-md-6">
			<h3 style="margin-bottom:15px;">{% trans "Assignments" %} </h3>
		</div>
		<div class="col-md-6"></div>
	</div>
	
	{% for x in user.assignment_set.all %}
		{% cycle '<div class="row">' '' %}
		<div class="col-md-6">
			<div class="panel panel-assignment">
				<div class="panel-heading">
					<h3 class="panel-title">
						<a href="{% url 'jobs_manager_app:assignment_detail' x.id %}" >
							{{x.name}}
							{% if x.int_state == 5 %}{% trans "(Closed)" %}{% endif %}
						</a>
					</h3>
				</div>
				<div class="panel-body">
					<div style="float: right; border: 1px solid gainsboro; border-radius: 3px; padding: 5px; margin-left: 5px; margin-bottom: 5px;" >
						{% trans "ETA:" %} {{ x.eta|default_if_none:"N/A" }}<br>
						{% trans "Price:" %} {{ x.price|default_if_none:"N/A" }} €
					</div>
					{{x.requirements|linebreaksbr}}
				</div>
			</div>
		</div>
		{% if forloop.last and not forloop.counter|divisibleby:2 %}
			<div class="col-md-6"></div>
			</div>
		{% endif %}
		{% cycle '' '</div>' %}
	{% endfor %}
</div>
{% endif %}

<!-- END ASSIGNMENTS -->



<!-- TASKS -->

{% if user.task_set.count != 0 %}
<div class="row">
	<div class="row">
		<div class="col-md-6">
			<h3 style="margin-bottom:15px;">{% trans "Tasks" %} </h3>
		</div>
		<div class="col-md-6"></div>
	</div>
	
	{% for x in user.task_set.all %}
		{% cycle '<div class="row">' '' %}
		<div class="col-md-6">
			<div class="panel panel-task">
				<div class="panel-heading">
					<h3 class="panel-title">
						<a href="{% url 'jobs_manager_app:task_detail' x.id %}" >
							{{x.name}}
							{% if x.bool_completed %}{% trans "(Completed)" %}{% endif %}
						</a>
					</h3>
				</div>
				<div class="panel-body">
					<div style="float: right; border: 1px solid gainsboro; border-radius: 3px; padding: 5px; margin-left: 5px; margin-bottom: 5px;" >
						{% trans "Priority:" %} {{ x.priority }}<br>
					</div>
					{{x.description|linebreaksbr}}
				</div>
			</div>
		</div>
		{% if forloop.last and not forloop.counter|divisibleby:2 %}
			<div class="col-md-6"></div>
			</div>
		{% endif %}
		{% cycle '' '</div>' %}
	{% endfor %}
</div>
{% endif %}

<!-- END TASKS -->



{% endblock content %}

src/jobs_manager_app/templates/jobs_manager_app/user_list.html
{% extends "jobs_manager_app/base.html" %}
{% load i18n %}

{% block content %}


<table class="table table-hover table-condensed">
	<tr>
		<th>{% trans "Username" %}</th>
		<th>{% trans "Group" %}</th>
		<th>{% trans "Last name" %}</th>
		<th>{% trans "First name" %}</th>
		<th>{% trans "email" %}</th>
		<th>{% trans "# projects" %}</th>
		<th>{% trans "# assignations" %}</th>
		<th>{% trans "# collaborations" %}</th>
		<th>{% trans "# comments" %}</th>
		<th>{% trans "Joined" %}</th>
	</tr>
	{% for user in user_list %}
	<tr>
		<td>
			<a href="{% url 'jobs_manager_app:user_detail' user.id %}"> {{ user.username }}</a>
		</td>
		<td>{{ user.groups.first }}</td>
		<td>{{ user.last_name }}</td>
		<td>{{ user.first_name }}</td>
		<td>{{ user.email }}</td>
		<td>{{ user.project_set.count }}</td>
		<td>{{ user.assignment_set.count }}</td>
		<td>{{ user.task_set.count }}</td>
		<td>{{ user.comment_set.count }}</td>
		<td>{{ user.date_joined|date:"M, Y" }}</td>
	</tr>
	{% endfor %}
</table>

{% endblock content %}